[project]
name = "map-poster-app"
version = "1.0.0"
description = "Create posters from city maps"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.2",
    "matplotlib>=3.10.8",
    "osmnx>=2.0.7",
]

[project.scripts]
start-app = "app:run_server"
